### PR TITLE
Fix import and export of sudokus

### LINKED ISSUE #103: Can't open downloaded .opensudoku files
Pixel 5, running Android 11. When I click on Import, and navigate to my Downloads, no files are listed, even though there are several .opensudoku files in there. I have granted media/file permissions when asked. Also, if I go the file browser and click on the file, three app choices appear, but none of them are Opensudoku. I don't know if it will help, but my only three choices are KeePassDroid, Stocard and OsmAnd+

### PR DESCRIPTION
**Pull request by autinerd**
Fixes #103 partly.

Because Android 11 changes a lot in terms of accessing files in external storage, there have to be some changes in handling import and export.

Export: Uses the Android system file picker to let to user select a path and writes the data into that file.
Import: Uses the Android system file picker to let the user select a file to import. Because the file name is not reliable, decides the format based on the first 512 bytes of the file content.

One downside is that the minimum Android version will be KitKat.

### CODE REVIEW

**Comment by autinerd** [comment]
It has now following behavior:
- Import and Export opens the system's file picker to let the user select a file
- Import format is now decided on file content, because of unreliable file names
- Opening a `.opensudoku` or `.sdm` file from File explorer seems to work now
- Minimum Android version is now KitKat (I tested with KitKat, 10 and 11)
- The Export Activity is now a progress bar

**Comment by ogarcia** [comment]
This is a great PR and I think that we can drop support to versions prior to kikat, but the import seems not work well if you try to open a file directly from web browser. Steps to reproduce:
1. Open app in emulator with Kitkat
2. Go to sudoku lists
3. Press in _Get More Puzzles Online_
4. Press in any file of list, for example in Easy (100 puzzles)
5. App crash

Can you try to fix this crash?

**Comment by autinerd** [comment]
I have now removed the http intent filters, because for download a extra background task would be needed. So now the browser downloads the file.
The file opening in the File Explorer just stooped working again for me, so I added now OpenSudoku in the Share panel, so that you can share the file you want to import and it will be imported.

The file opening is very horrible, you never know if it will work or not.

**Comment by ogarcia** [comment]
The problem in File Explorer is caused because it don't send full filename so in some android devices (and versions) works and in others not.

With latest change the import don't work anymore because `String action = intent.getAction();` can be `null` :hankey:

**Comment by autinerd** [comment]
> With latest change the import don't work anymore because `String action = intent.getAction();` can be `null`

Is fixed :)

**Comment by MrGibbage** [comment]
Worked perfectly on my Pixel 5/Android 11. Thanks!

**Pull request merged**
