### PR TITLE
Select first note if no big numbers

### LINKED ISSUE #69: When selecting a digit with no filled cells, notes containing that digit are not highlighted.
If one digit is not present on the board, but is used in notes, selecting that digit in SN mode does not highlight the cells with those notes. 

To replicate the issue:
1) Start a game where one or more digits are not present.
2) Choose SN mode and note mode, then select a digit that's not present on the board.
4) Place a note in an empty cell.
5) Choose a digit that's already in a filled cell.
6) Choose the digit of the note again.
7) Notice that the digit chosen in step 5) is still highlighted, and the notes with the digit you chose in step 6) are not.

### PR DESCRIPTION
**Pull request by byronigoe**
Fixes #69

### CODE REVIEW

**Comment by ogarcia** [comment]
Thanks! Along this week I'll merge it :wink:

**Comment by ogarcia** [comment]
Sorry, but this not fixes #69 

If I select a digit not present in board this doesn't highlight the cells with those notes, this PR only makes the digit key unusable. Maybe you have a mistake?

**Comment by byronigoe** [comment]
Nope. I tested again and this resolves the issue. The only difference is that I'm building against SDK 29.

**Comment by ogarcia** [comment]
I found better solution to this. Anyway thanks for your PR

**Pull request closed without merging**
