### PR TITLE
Puzzle solver

### PR DESCRIPTION
**Pull request by steve3424**

### CODE REVIEW

**Comment by ogarcia** [comment]
Hi Steve,

This is a great contribution, but please change your pull request to develop branch.

The only problem that I have now is that cannot upload changes to Google Play Store because first for all I must fix #30 and I not have time to do it. If you want help on these issue you are welcomed.

Thanks again for your first contribution :wink:

**Comment by steve3424** [comment]
Thanks for the feedback. I will definitely look into that issue and I will change this pull request.

**Comment by steve3424** [comment]
Hey Oscar,
I was wondering if you had any trouble with the develop branch. I want to
look into issue #30, but I can't get the code from the develop branch to
run on my emulator. I have played around and it has something to do with
the 'android:theme' in the manifest, but I can't find a fix. Were you able
to run the code without issue?

Thanks,
Steve

**Comment by ogarcia** [comment]
Hi Steve,

Develop branch is, well, a develop branch. I remember when I merge #29 that it worked in emulator with old versions of Android (for example 4, or 5) but in new versions (from 6.0 onwards) it don't work cause of #30. The code lacks the permissions requesting and cannot be executed.

**Comment by steve3424** [comment]
Hey Oscar,

Ok haha I understand. I was under the impression that the latest code was working it just didn’t ask for the permission. So I was thinking I had something wrong on my end. Thanks for the info I appreciate it!

Steve

**Pull request closed without merging**
