### PR TITLE
Add Github Actions Gradle build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/gliptak/opensudoku/pull/1/checks?check_run_id=449613236

### CODE REVIEW

**Comment by gliptak** [comment]
@ogarcia please review

**Comment by ogarcia** [comment]
The PR must be in develop not in master. Anyway, the gradle build is done before any push, I don't see the sense of this PR.

**Comment by jlnordin** [comment]
I see this was closed, but I did have a few comments:

1. It looks like this PR is set to automatically run test code anytime
master is updated. That's pretty cool.

2. I don't think there are any automated  tests in open sudoku. It might be
good to have some, but I don't think the gradle test task would actually do
anything. Maybe if we had tests this github action would make more sense?

3. This could be used to automatically build in the cloud everytime master
is updated. Sure, master is locally verified, but building automatically
has its merits too.

My two cents. :-)

**Comment by gliptak** [comment]
@jlnordin currently this is configured to build all PRs (green checkmark) and the master when updated. While there no tests currently, compilation success is additional information which is not present for this project currently. After merging, we can update to publish a "release" APK on each master commit.

**Comment by jlnordin** [comment]
I quite like automatically building all PRs.

Oscar, thoughts?

**Comment by ogarcia** [comment]
The _automagical_ builds can be done with any CD/CI, but the APK must be signed and, for security reasons, this cannot be done in a PR because not have control about code in PR and could be malicious.

If we had automated test then this have more sense.

I could set up an automatic build for every tag, but without unit tests I don't see the advantage because is a work that I'm doing already to upload the new versions to Play Store.

**Comment by gliptak** [comment]
@ogarcia committers of this repo have control of what is pushed to the ```master``` branch.

You could upload debug and/or release certs as secrets and build/release signed APKs (for ```master``` branch only)

https://medium.com/better-programming/ci-cd-for-flutter-apps-using-github-actions-b833f8f7aac
https://github.com/nabilnalakath/flutter-githubaction

**Comment by ogarcia** [comment]
@gliptak this is what I commented when say: _I could set up an automatic build for every tag..._

**Pull request closed without merging**
