### PR TITLE
Title screen and "resume" feature

### PR DESCRIPTION
**Pull request by jlnordin**
This PR adds a title screen as the primary launcher activity to Open Sudoku with a new "resume" feature to start the most recently played game. I find this very helpful to avoid clicking through 2-4 screens to pick up where I left off.

I also moved the "what's new" dialog to the title screen activity since this is intended to be the landing page for all app launches now.

Title Screen

Scenarios Tested
====
- Verified navigating back and forth between the title screen and the folder lists activity.
- Verified the title screen works with different themes.
- Verified the "what's new" dialog on first launch shows up on the title screen and not the lists activity.

### CODE REVIEW

**Comment by jlnordin** [comment]
Note that this PR will conflict with the note highlighting PR since they both add strings. Whichever PR is accepted first, I'll be sure to fix the merge conflicts of the other one.

**Comment by ogarcia** [comment]
Merged! Tell me when you want make a new play store version :wink:

**Comment by jlnordin** [comment]
I'd say now is a good time for a new version in the store. :-)

**Comment by jlnordin** [comment]
Oscar, when you upload the next version, would it be possible to update
some of the screen shots on the play store with some of the new themes?

Thanks!

**Comment by ogarcia** [comment]
Yes, no problem. ;-)

**Comment by Porrumentzio** [comment]
I don't know whether to create a new issue or post my comment here.

This feature is great, but I have a improvement to it: **hide** this button **when** the last sudoku was **resolved**!

**Pull request merged**
