### PR TITLE
Lots of maintenance

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Android Studio 3.0.1 -> 3.2.1
- Gradle 4.1 -> 5.0
- Target Android Pie
- Java 1.8 compatibility (lambdas, methods, etc.)
- Reformat code
- Migrate app to appCompat
- Migrate to AndroidX

### CODE REVIEW

**Comment by ogarcia** [comment]
WOW! Thanks @TacoTheDank !!!

Now I'm on holidays, but I'll back in second week of January and will merge and upload it.

**Comment by TacoTheDank** [comment]
Sounds great... thanks! The only thing you'll probably have to do is add the Sdk 23+ permission checks, because I don't really know how to do that yet.

**Comment by ogarcia** [comment]
Please @TacoTheDank add you as contributor in readme and in strings.xml

**Comment by TacoTheDank** [comment]
gotchu

**Comment by TacoTheDank** [comment]
:)

**Pull request merged**
