### PR TITLE
Fix issue #30 + other fixes

### PR DESCRIPTION
**Pull request by steve3424**
I was having trouble with the latest commits of the develop branch. It had something to do with the theme. I changed the theme and changed 2 of the ListActivity classes to AppCompatActivity classes. It is now working as far as I can tell. There are still a few issues that I am working on.

### CODE REVIEW

**Comment by steve3424** [comment]
I just added the permission requests needed to fix issue #30 

I believe the transition from ListActivity to AppCompatActivity caused a new issue where the context menu isn't working, but I will look into this.

**Comment by steve3424** [comment]
fixed

**Comment by steve3424** [comment]
fixed problem where the pop up keyboard was causing app to crash

**Comment by steve3424** [comment]
added solver feature

**Comment by ogarcia** [comment]
Great work! Tell me when you finish this pull request to merge it. And add you in Contributors section of README :wink:

**Comment by steve3424** [comment]
Thanks! It is finished now. Are you able to put this on Google Play store now?

**Comment by ogarcia** [comment]
> Thanks! It is finished now. Are you able to put this on Google Play store now?

I think yes. But I'm _AFK_ until next weekend. At these moment I'll do the tests and upload it.

**Comment by steve3424** [comment]
Great! Let me know if there are any problems.

Also when I first read your message I read it as saying that I was supposed to add my self to the README so I did. Then I re-read it and i think you were saying you will do that right?

**Comment by ogarcia** [comment]
No, you can do it. I think that [this commit](https://github.com/ogarcia/opensudoku/commit/f8665ea7b112a606b34fa272f93c1d92e4c06c57) is perfect.

**Comment by steve3424** [comment]
Ok great I will put that commit up

**Comment by ogarcia** [comment]
Hi Steve, I can merge this PR, but I found a small issue, if you put a wrong number in a cell and try to use solver, nothing happens. I think that when solver cannot solve the puzzle (because some is wrong) it must display a warning message.
Another issue is that if you finish a puzzle and press restart option, the solver option remains deactivated. You must exit and enter again to use option.

Tell me what do you do. You prefer fix this issues now or want to merge this pull request and open a new one in the future?

**Comment by steve3424** [comment]
Thanks for letting me know. I will look this afternoon and send you an email tonight if that’s ok.

**Comment by steve3424** [comment]
Fixed both issues. If there are any others you find let me know.

**Pull request merged**
