### PR TITLE
Cell protection against occassional overwrtie

### PR DESCRIPTION
**Pull request by pan64**
solves issue #14

### CODE REVIEW

**Comment by ogarcia** [comment]
Thanks for this pull request!

I think that's better ask for overwrite than simply lock the entry, because if you have a mistake you must enter settings, disable option, perform modify, go settings and enable again.

**Comment by pan64** [comment]
Hi,
what do you think. It should work only in SingleNumber input mode (or
independently, for every IM)?

Thanks

On Sat, Jun 26, 2021 at 7:07 PM Óscar García Amor  <

**Comment by ogarcia** [comment]
I think, for consistency, that is better in every entry mode

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this PR. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) following the [contributing guide](https://gitlab.com/opensudoku/opensudoku/-/blob/develop/CONTRIBUTING.md).

Thank you very much for your understanding.

**Pull request closed without merging**
