### PR TITLE
Basque (eu) translation added and reordered strings

### PR DESCRIPTION
**Pull request by Porrumentzio**
I created `/values-eu/strings.xml` and also reordered that file and the original one, `/values/strings.xml`, in order to have the _titles_ before _summaries_.

I hope that's not problem. If yes, I'll change them rapidly!

### CODE REVIEW

**Comment by ogarcia** [comment]
No problem with reorder, but you must reorder other translation files too :pray:

**Comment by Porrumentzio** [comment]
The only what I reordered were some strings between versions `3.0.0` and `3.3.0`, so there are translations that do **not** have them. What should I do on them?

**Comment by Porrumentzio** [comment]
Also [german translation](https://github.com/ogarcia/opensudoku/blob/master/app/src/main/res/values-de/strings.xml) is completely disordered and without version comments. Same for hungarian.

**Comment by Porrumentzio** [comment]
Reordered `es`, `fr` and reordered and version-commented `hu` to coincide with _original_ and `eu`. Now all* updated translations have the same order on strings.

\* `de` is absolutely disordered, so I'm not gonna take the work to reorder that one.

The other ones:
`cs`, `it`, `pt`, `pt-rBR`, `sv`, `tr` and `zh-rCN` (no version-comments) has not those strings, they're stacked on `2.5.0`

**Pull request merged**
